### ISSUE TITLE
[All] feat/realtime_debate

### ISSUE THREAD

**Issue by YuchanJeong** [codestates/debate-ducks#104]
### ISSUE
- Group:  `Client`, `Server`
- Type: `Feat`
- Detail: 실시간 토론 진행 기능 구현

### TODO
1. [x] 자신 차례일 때 화면 공유 시 적절한 비율로 조정하여 큰 화면으로 공유
2. [x]  양측 동의 하에 토론 시작
3. [x] 토론 진행과 적절한 안내 및 타이머

### Estimated time
- `3h + 𝜶`
