### ISSUE TITLE
[Server] feat/column-router

### ISSUE THREAD

**Issue by ParkSangBong** [codestates/debate-ducks#17]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Detail: 칼럼 라우터 및 컨트롤러 구현

### TODO
1. [x] 라우터 작성
2. [x] 컨트롤러 작성
3. [x] 로컬 환경에서 테스트 및 확인
4. [x] 클라이언트와 병합후 통합환경에서 테스트 및 확인
5. [x] 배포 환경에서 테스트 및 확인

### Estimated time
- `3h`
