### ISSUE TITLE
[Client] feat/card-components

### ISSUE THREAD

**Issue by strawberryoolongtea** [codestates/debate-ducks#49]
### ISSUE
- Group:  `Client`
- Type: `Feat`
- Detail: card 관련 컴포넌트 제작

### TODO
1. [x] box card 컴포넌트 제작 (배너 card 공통 컴포넌트)
2. [x] 포럼 관련 card item 컴포넌트 제작
3. [x] 커뮤니티 관련 card item 컴포넌트 제작
4. [x] 랭킹 관련 card item 컴포넌트 제작
5. [x] likey 컴포넌트 제작
6. [x] voted 컴포넌트 제작
7. [x] debate card 컴포넌트 제작

### Estimated time
- `3h + 𝜶`
