### ISSUE TITLE
[Client] Initialize project

### ISSUE THREAD

**Issue by ParkSangBong** [codestates/debate-ducks#6]
### ISSUE
- Group:  `Client`
- Type: `Init`
- Detail: 프로젝트 초기 설정(클라이언트)

### TODO
1. [x] React App 생성
2. [x] favicon 설정 및 기본 meta 정보 작성
3. [x] Style reset 적용
4. [x] Font-family 설정
5. [x] Prettier 및 EsLint 설정
6. [x] .gitignore 설정
7. [x] Tailwind CSS 설정
8. [x] 기본 구조 설정(폴더 및 파일) 및 axios 설치 
9. [x] 라우팅 설정(react-router-dom)
10. [x] Redux-toolkit 설정

### Estimated time
- `3h`
