### ISSUE TITLE
[All] feat/realtime_debate_pre

### ISSUE THREAD

**Issue by YuchanJeong** [codestates/debate-ducks#76]
### ISSUE
- Group:  `Client`, `Server`
- Type: `Feat`
- Detail: DebateRoom의 토론 시작 전의 기본적인 기능 및 디자인 완성

### TODO
1. [x] 뒤로가기 및 새로고침으로 인한 에러 방지
2. [x] 모달 및 버튼 제작
3. [x] 화면 공유 기능 제작
4. [x] Pros와 Cons 구분
5. [x] CSS 완성
6. [x] 원하는 배치와 디자인으로 녹화하기 위해서 Canvas에 비디오 및 기타 요소들을 그려서 하나의 스트림으로 만듦
   
### Estimated time
- `3h + 𝜶`
